---
loopback: 100.0.0.174
global_asn: 65534
local_asn: 65174
neighbors:
   - interface: et-0/0/0
     name: poc-qfx5110-169
     peer_interface: et-0/0/1
     asn: 65169
     peer_ip: 100.0.0.13 
     local_ip: 100.0.0.12
     peer_loopback: 100.0.0.169
   - interface: et-0/0/1  
     name: poc-qfx5110-170
     peer_interface: et-0/0/1
     asn: 65170
     peer_ip: 100.0.0.15
     local_ip: 100.0.0.14
     peer_loopback: 100.0.0.170
   - interface: et-0/0/2
     name: poc-qfx5110-171
     peer_interface: et-0/0/1
     asn: 65171
     peer_ip: 100.0.0.17
     local_ip: 100.0.0.16
     peer_loopback: 100.0.0.171
