---
loopback: 100.0.0.170
iso_loopback: 49.0001.0001.0001.0170.00
global_asn: 65534
local_asn: 65170
neighbors:
   - interface: et-0/0/0
     name: poc-qfx5110-172
     peer_interface: et-0/0/1
     asn: 65172
     peer_ip: 100.0.0.4 
     local_ip: 100.0.0.5
     peer_loopback: 100.0.0.172
   - interface: et-0/0/1  
     name: poc-qfx5110-174
     peer_interface: et-0/0/1
     asn: 65174
     peer_ip: 100.0.0.14
     local_ip: 100.0.0.15
     peer_loopback: 100.0.0.174
   - interface: et-0/0/2
     name: poc-qfx5110-175
     peer_interface: et-0/0/1
     asn: 65175
     peer_ip: 100.0.0.24
     local_ip: 100.0.0.25
     peer_loopback: 100.0.0.175
   - interface: et-0/0/3
     name: poc-qfx5110-188
     peer_interface: et-0/0/1
     asn: 65188
     peer_ip: 100.0.0.34
     local_ip: 100.0.0.35
     peer_loopback: 100.0.0.188
   - interface: et-0/0/4
     peer_interface: et-0/0/1
     name: poc-qfx5110-189
     asn: 65189
     peer_ip: 100.0.0.44
     local_ip: 100.0.0.45
     peer_loopback: 100.0.0.189
