---
ADMUSER: lab
ADMPASS: jnpr!123

credentials:
  host: "{{ inventory_hostname }}"
  username: lab
  password: jnpr!123
  timeout: 20
# you can remove username and password from credentials, and use environment variables. In that case, here's how to set them in your ansible server:   
# ANSIBLE_NET_USERNAME=username
# echo $ANSIBLE_NET_USERNAME 
# ANSIBLE_NET_PASSWORD=password
# echo $ANSIBLE_NET_PASSWORD 
# export ANSIBLE_NET_USERNAME 
# export ANSIBLE_NET_PASSWORD 
# printenv | grep ANSIBLE

